### ISSUE TITLE
[MILESTONE CHECKLIST] 1. Html book locally built

### ISSUE THREAD

**Issue by NatalieZelenka** [NatalieZelenka/phenotype_from_genotype#1]
To-do:
- [x] Organise GitHub
    - [x] Plan milestones (at least up to the one after this)
    - [x] Change branch name to `main`
    - [x] Feature branches for chapters
------------------
- [x] Intro page (#2, #10)
- [x] Front Matter (#6, #9) 
- [x] Chapters
    - [x] Chapter 1: Introduction (#11 ,#12)
    - [x] Chapter 2: Biological background (#3, #13 + #20)
    - [x] Chapter 3: Computational biology background (#15, #21)
    - [x] Chapter 4: Phenotype predictor (#16, #31)
    - [x] Chapter 5: Combined dataset (#17, #28)
    - [x] Chapter 6: Filter (#18, #29)
    - [x] Chapter 7: Conclusions (#19, #29)
- [x] References (, #12)

This milestone does not:
- include improvements to any chapters content.
- interactive content
