### ISSUE TITLE
[MILESTONE CHECKLIST] 2. First pass polish of chapter 8

### ISSUE THREAD

**Issue by NatalieZelenka** [NatalieZelenka/phenotype_from_genotype#25]
# Chapter 8: Combining gene expression data sets
This is a milestone rather than just an issue since this will be the first chapter that is properly finished and that I  will commit to not refactoring, changing, or adding to... and that's going to be a big deal: *deep breath*.

## Preparations
- [x] Read through and plan (#38)
---
## Chapter to-do
- [x] A once over of the structure, and quality of the written sections.
    - [x] Introduction
    - [x] Background
    - [x] Ontolopy (#33, )
        - [x] Ontolopy polished into a proper thing that is properly released on pypi with a sphinx website (#33,)  https://github.com/NatalieThurlby/ontolopy
            - [x] Basic documentation (sphinx)
            - [x] Roadmap
            - [x] Tests (minimal)
            - [x] Website (sphinx)
            - [x] Can be pip'd into #34
    - [x] Future work
- [x] All research for this chapter finished/in ipynb/reproducible:
    - [x] Data acquisition (#39, )
    - [x] Data wrangling (#34)
    - [x] Results 
Moved to appendix:
    - [x] Test data simulation (add as separate R ipynb?)
Moved to future work:
    - [x] Batch Correction 

---
## Checklist
- [x] Citations done
- [x] Cross-references to other parts of the book
- [x] Figures, captions and references in text done
- [x] TODOs for other sections based on this chapter (e.g. in intro/abstract/discussion) written.
- [x] Headings sorted (right amount of ## everywhere)
---
## Not doing here
It's okay not to have finished:
* some signposting text/cross-references to later chapters (since it will be easier to do this after later chapters are done).
* nice-to-haves like epigraphs, fun asides, hand-illustrations
* complete polish (i.e. of word choice, things like active/passive, decisions on how to refer to certain things, acronyms explained, etc)
* Binder links: since I should try an easier (non-R) chapter first.
* Interactive figure captions
* IRkernel figure captions
* Every single TODO
