### ISSUE TITLE
[MILESTONE CHECKLIST] 4. Finished draft

### ISSUE THREAD

**Issue by NatalieZelenka** [NatalieZelenka/phenotype_from_genotype#27]
At the end of this checkpoint the thesis should be basically completely done. And ready to submit, except for any outstanding frills

- [x] Put this repo online and make sure book renders online properly
     - [x] Add GH actions to make the repo automatically update to the `gh-pages` branch
     - [x] Added `.nojekyll` and redirect `index.html` to `gh-pages` branch.
