### ISSUE TITLE
Main checklist

### ISSUE THREAD

**Issue by NatalieZelenka** [NatalieZelenka/phenotype_from_genotype#49]
## Current to-dos:
- [x] Get Ontolopy chapter rendering on web
  - [x] Try new Ontolopy release (this worked) #51
- [x] Check for any VIP todo comments 
- [x] Pull in the big PR
- [x] Check the license for each section, and be explicit about what it covers, e.g. code/text especially Snowflake
- [ ]  pin requirements exact versions using pigar
