### ISSUE TITLE
[MILESTONE CHECKLIST] 5. Ready to submit

### ISSUE THREAD

**Issue by NatalieZelenka** [NatalieZelenka/phenotype_from_genotype#8]
## Finishing touches
- [x] Built PDF and checked, any necessary frills added:
   - [x] TOC (#7, )
   - [x] Make PDF downloadable on GitHub/Jupyter Book and make sure that examiners know where to go for latest version in submitted PDF.
- [x] Once overs (read-through and make minor fix notes).
    - [x] Intro to jupyter-book (how it works/why I did it)
    - [x] Front matter
        - [x] Update word count
        - [x] Update date
        - [x] Do something with signature declaration?
    - [x] Chapter 1
    - [x] Chapter 2
    - [x] Chapter 3
    - [x] Chapter 4
    - [x] Chapter 5
    - [x] Chapter 6
    - [x] Chapter 7
- [x] Consistency checks.
    - [x] Check names of software are written properly (e.g. Jupyter Book) and cited.
    - [ ] Check how I refer to chapters - what case: do I say "Chapter 1"? "this Chapter" or "this chapter?")
    - [ ] Make sure acronyms have been defined at first use and added to a glossary if I have one
    - [ ] Check external links resolve `jupyter-book build mybookname/ --builder linkcheck`
- [ ] Credit
  - [x] Permission to reproduce images
  - [x] All software cited
      - [x] IRKernel
      - [x] JupyterBook 
      - [x] Jupyter Notebook
      - [ ] Binder/MyBinder
---
## Unecessary details
(Deciding not to do anything in this section is as much of a success as doing it and I get to tick it)
- [x] Illustrations
   - [x] Alternative bristol logo with aside about knobheads.
- [ ] Glossary
- [x] Interactivity
- [ ] Bibtex faffing
   - [ ] Add Patent type
   - [ ] Wayback machine backup web links
- [x] Asides about knobhead eugeneticists, e.g. fischer
---
## Organisation
- [ ] Organised viva
- [ ] Submitted that mofo
- [ ] Organised thank-yous for Kate/Patty, Oliver, Julian, etc.
